"""Shared machinery for scripts/self_audit.py and scripts/release_audit.py.

Four states, and the difference between the last two matters:

    PASS          the property was checked and holds
    PARTIAL       the property holds only in part, with the gap named
    FAIL          the property was checked and does not hold
    NOT EXECUTED  the check could not run here (infrastructure absent, optional tool missing).
                  Never silently upgraded to PASS — "we could not test this" is a distinct,
                  visible outcome.
"""
from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "reports" / "results"

PASS = "PASS"
PARTIAL = "PARTIAL"
FAIL = "FAIL"
NOT_EXECUTED = "NOT EXECUTED"
STATES = (PASS, PARTIAL, FAIL, NOT_EXECUTED)


@dataclass
class Row:
    category: str
    check: str
    state: str
    evidence: str


@dataclass
class Recorder:
    rows: List[Row] = field(default_factory=list)

    def add(self, category: str, check: str, state: str, evidence: str) -> None:
        if state not in STATES:
            raise ValueError(f"invalid audit state {state!r}")
        # Evidence is quoted verbatim into a committed report, so the repo root — which differs on
        # every machine — is rewritten to a relative marker before it can be baked in.
        text = str(evidence).replace(str(ROOT) + "/", "./").replace(str(ROOT), ".")
        self.rows.append(Row(category, check, state, text))

    def counts(self) -> Dict[str, int]:
        return {s: sum(1 for r in self.rows if r.state == s) for s in STATES}

    def exit_code(self) -> int:
        """FAIL is fatal. NOT EXECUTED is reported, not fatal — it is honest, not broken."""
        return 1 if self.counts()[FAIL] else 0

    def markdown(self, title: str, generated_by: str, timestamp: str,
                 extra: Optional[List[str]] = None) -> str:
        c = self.counts()
        lines = [f"# {title}", "",
                 f"_Generated by `{generated_by}` on {timestamp}._", "",
                 f"**{c[PASS]} PASS · {c[PARTIAL]} PARTIAL · {c[FAIL]} FAIL · "
                 f"{c[NOT_EXECUTED]} NOT EXECUTED**", "",
                 "`NOT EXECUTED` means the check could not run in this environment (for example no "
                 "Hadoop cluster or no browser). It is never counted as a pass.", "",
                 "| Category | Check | Result | Evidence |", "|---|---|---|---|"]
        for r in self.rows:
            ev = r.evidence.replace("|", "\\|").replace("\n", " ")
            lines.append(f"| {r.category} | {r.check} | **{r.state}** | {ev} |")
        if extra:
            lines += [""] + extra
        return "\n".join(lines) + "\n"

    def to_json(self) -> Dict[str, Any]:
        return {"counts": self.counts(),
                "rows": [{"category": r.category, "check": r.check, "state": r.state,
                          "evidence": r.evidence} for r in self.rows]}

    def print_summary(self) -> None:
        for r in self.rows:
            print(f"{r.state:13} {r.category}: {r.check}")
        print(f"\n{self.counts()}")


# --------------------------------------------------------------------------- loading
def load_result(name: str) -> Optional[dict]:
    p = RESULTS / name
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text())
    except json.JSONDecodeError:
        return None


def read_text(path: Path) -> str:
    try:
        return path.read_text(errors="ignore")
    except Exception:
        return ""


# --------------------------------------------------------------------------- environment probes
def storage_state() -> Dict[str, Any]:
    sys.path.insert(0, str(ROOT))
    from vigil.config import load_config
    from vigil.storage.backend import storage_status

    return storage_status(load_config()).to_dict()


def mapreduce_state() -> Dict[str, Any]:
    sys.path.insert(0, str(ROOT))
    from vigil.config import load_config
    from vigil.mapreduce.hadoop_runner import mapreduce_status

    return mapreduce_status(load_config())


def run_pytest(extra_args: Optional[List[str]] = None, timeout: int = 2400) -> Dict[str, Any]:
    cmd = [sys.executable, "-m", "pytest", "tests", "-q", "--no-header",
           "-p", "no:cacheprovider"] + (extra_args or [])
    try:
        proc = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, timeout=timeout)
    except Exception as exc:
        return {"executed": False, "detail": f"{type(exc).__name__}: {exc}", "stdout": ""}
    tail = proc.stdout.strip().splitlines()[-1] if proc.stdout.strip() else ""
    def grab(pattern: str) -> int:
        m = re.search(pattern, tail)
        return int(m.group(1)) if m else 0
    return {"executed": True, "returncode": proc.returncode, "summary": tail,
            "passed": grab(r"(\d+) passed"), "failed": grab(r"(\d+) failed"),
            "errors": grab(r"(\d+) error"), "skipped": grab(r"(\d+) skipped"),
            "stdout": proc.stdout}


def ui_smoke_available() -> bool:
    return (ROOT / "node_modules" / "jsdom").exists() and shutil.which("node") is not None


def run_ui_smoke(timeout: int = 600) -> Dict[str, Any]:
    """Run the `npm run ui-smoke` entry point (boots the API, renders in jsdom, stops it).

    Returns executed=False when jsdom or node is missing. Never a browser: no layout or paint.
    """
    if not ui_smoke_available():
        return {"executed": False,
                "detail": "jsdom not installed (run `npm install` in the repo root) or node missing"}
    env = dict(os.environ)
    try:
        proc = subprocess.run(["node", "tests/run_ui_smoke.mjs"], cwd=ROOT, capture_output=True,
                              text=True, timeout=timeout, env=env)
    except Exception as exc:
        return {"executed": False, "detail": f"{type(exc).__name__}: {exc}"}
    return {"executed": True, "returncode": proc.returncode,
            "stdout": proc.stdout, "stderr": proc.stderr,
            "summary": (proc.stdout.strip().splitlines() or ["no output"])[-1]}


def browser_automation_available() -> Optional[str]:
    """Return the name of an available browser-automation stack, or None."""
    try:
        import playwright  # noqa: F401
        return "playwright"
    except Exception:
        pass
    try:
        import selenium  # noqa: F401
        if shutil.which("chromedriver") or shutil.which("geckodriver"):
            return "selenium"
    except Exception:
        pass
    return None


# --------------------------------------------------------------------------- repo scans
SCAN_SUFFIXES = {".py", ".md", ".js", ".mjs", ".html", ".css", ".yaml", ".yml", ".json",
                 ".txt", ".sh", ".ps1", ".toml", ".cfg"}
# `data/` is NOT skipped wholesale any more: v1.0.0 shipped `_vigil_manifest.json` files holding
# the build machine's absolute path, and excluding the directory hid it. Binary datasets are
# skipped by suffix instead, so generated JSON/text metadata under data/ is inspected.
SKIP_DIRS = {".git", "node_modules", "__pycache__", ".pytest_cache", ".venv", ".ruff_cache"}
BINARY_SUFFIXES = {".parquet", ".pq", ".bson", ".db", ".pkl", ".joblib", ".npy", ".npz",
                   ".png", ".jpg", ".jpeg", ".gif", ".pdf", ".zip", ".gz", ".ico", ".woff",
                   ".woff2", ".ttf", ".xlsx", ".docx", ".pptx"}
# Large generated payloads that are data, not release metadata: scanned for paths but never
# quoted wholesale, and only when they are text.
MAX_SCAN_BYTES = 8 * 1024 * 1024


# The audits quote their own findings verbatim, so scanning their output would re-report
# yesterday's hit forever. The generated audit reports are excluded; their *inputs* are not.
SELF_REFERENTIAL = {"reports/SELF_AUDIT.md", "reports/RELEASE_AUDIT.md",
                    "reports/results/self_audit.json", "reports/results/release_audit.json"}


def scan_files() -> List[Path]:
    out = []
    for p in ROOT.rglob("*"):
        if p.is_dir() or any(part in SKIP_DIRS for part in p.relative_to(ROOT).parts):
            continue
        if p.relative_to(ROOT).as_posix() in SELF_REFERENTIAL:
            continue
        suffix = p.suffix.lower()
        if suffix in BINARY_SUFFIXES:
            continue
        if suffix in SCAN_SUFFIXES or p.name == "_vigil_manifest.json":
            try:
                if p.stat().st_size > MAX_SCAN_BYTES:
                    continue
            except OSError:  # pragma: no cover - race with a concurrent run
                continue
            out.append(p)
    return sorted(out)


SECRET_RE = re.compile(r"(api[_-]?key|secret|password|token)\s*[:=]\s*['\"][A-Za-z0-9/+_\-]{12,}", re.I)
# Absolute paths that would only exist on the machine that built the repo.
MACHINE_PATH_RE = re.compile(r"(/home/[a-z0-9_.-]+/|/Users/[A-Za-z0-9_.-]+/|[A-Z]:\\\\Users\\\\)")


def find_secrets() -> List[str]:
    hits = []
    for p in scan_files():
        if p.name == ".env.example":
            continue
        body = read_text(p)
        for m in SECRET_RE.finditer(body):
            if "your-" in m.group(0).lower() or "example" in m.group(0).lower():
                continue
            hits.append(f"{p.relative_to(ROOT)}: {m.group(0)[:48]}")
    return hits


def find_machine_paths() -> List[str]:
    hits = []
    for p in scan_files():
        if p.name in {"_audit_common.py"}:
            continue
        for i, line in enumerate(read_text(p).splitlines(), 1):
            m = MACHINE_PATH_RE.search(line)
            if m:
                hits.append(f"{p.relative_to(ROOT)}:{i}: {line.strip()[:80]}")
    return hits
